managers:
  - apt-get
  - brew
  - dnf
  - yay
  - pacman

apt-get:
  install: sudo apt install -y
  remove: sudo apt remove -y
  update: sudo apt update -y && sudo apt upgrade -y
  packages:
    python3: python3 python3-pip

brew:
  install: brew install
  remove: brew remove
  update: brew update && brew upgrade
  packages:
    python3: python
    kotlin: kotlin

dnf:
  install: sudo dnf install -y
  remove: sudo dnf remove -y
  update: sudo dnf update -y && sudo dnf upgrade -y
  packages:
    python3: python3 python3-pip

yay:
  install: yay -S --noconfirm
  remove: yay -R --noconfirm
  update: yay -Syu --noconfirm
  packages:
    python3: python3 python-pip

pacman:
  install: sudo pacman -S --noconfirm
  remove: sudo pacman -R --noconfirm
  update: sudo pacman -Syu --noconfirm
  packages:
    python3: python3 python-pip



system_manager: brew
