managers:
  - apt-get
  - brew
  - dnf
  - yay
  - pacman
  - scoop

apt-get:
  install: sudo apt install -y
  remove: sudo apt remove -y
  update: sudo apt update -y && sudo apt upgrade -y
  packages:
    python: python3 python3-pip
    nodejs: nodejs npm
    java: penjdk-17-jdk
    nextcloud: nextcloud-desktop
    firefox: firefox-esr

brew:
  install: brew install
  remove: brew remove
  update: brew update && brew upgrade
  packages:
    java: openjdk
    nodejs: nodejs npm
    firefox: --cask firefox
    brave: --cask brave-browser
    vscode: --cask visual-studio-code
    github: --cask github
    discord: --cask discord
    obsidian: --cask obsidian


dnf:
  install: sudo dnf install -y
  remove: sudo dnf remove -y
  update: sudo dnf update -y && sudo dnf upgrade -y
  packages:
    python: python3 python3-pip
    java: java-17-openjdk
    nodejs: nodejs npm

yay:
  install: yay -S --noconfirm
  remove: yay -R --noconfirm
  update: yay -Syu --noconfirm
  packages:
    python: python3 python-pip
    java: jdk-openjdk
    nextcloud: nextcloud-client
    vscode: visual-studio-code-bin
    github: github-desktop-bin

pacman:
  install: sudo pacman -S --noconfirm
  remove: sudo pacman -R --noconfirm
  update: sudo pacman -Syu --noconfirm
  packages:
    python: python3 python-pip
    nodejs: nodejs npm
    java: jdk-openjdk
    nextcloud: nextcloud-client

scoop:
  install: scoop install
  remove: scoop uninstall
  update: scoop update
  packages:
    python: python310
    java: jdk


npm:
 sass: sass
 typescript: typescript
 angular: '@angular/cli'


system_manager: brew

